// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldCupStickers.Data;

#nullable disable

namespace WorldCupStickers.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603053455_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorldCupStickers.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("CantidadCromos")
                        .HasColumnType("int");

                    b.Property<bool>("EdicionEspecial")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Albumes");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Cromo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCromo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMercado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("JugadorId");

                    b.HasIndex("NumeroCromo")
                        .IsUnique();

                    b.ToTable("Cromos");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnioFundacion")
                        .HasColumnType("int");

                    b.Property<string>("DirectorTecnico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GrupoMundialista")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroCamiseta")
                        .HasColumnType("int");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoFifa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Continente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RankingFifa")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoFifa")
                        .IsUnique();

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WorldCupStickers.Models.UsuarioCromo", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("CromoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaAdquisicion")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId", "CromoId");

                    b.HasIndex("CromoId");

                    b.ToTable("UsuarioCromos");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Cromo", b =>
                {
                    b.HasOne("WorldCupStickers.Models.Album", "Album")
                        .WithMany("Cromos")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupStickers.Models.Equipo", "Equipo")
                        .WithMany("Cromos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorldCupStickers.Models.Jugador", "Jugador")
                        .WithMany("Cromos")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Equipo");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Equipo", b =>
                {
                    b.HasOne("WorldCupStickers.Models.Pais", "Pais")
                        .WithMany("Equipos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Jugador", b =>
                {
                    b.HasOne("WorldCupStickers.Models.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("WorldCupStickers.Models.UsuarioCromo", b =>
                {
                    b.HasOne("WorldCupStickers.Models.Cromo", "Cromo")
                        .WithMany("UsuarioCromos")
                        .HasForeignKey("CromoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorldCupStickers.Models.Usuario", "Usuario")
                        .WithMany("UsuarioCromos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cromo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Album", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Cromo", b =>
                {
                    b.Navigation("UsuarioCromos");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Equipo", b =>
                {
                    b.Navigation("Cromos");

                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Jugador", b =>
                {
                    b.Navigation("Cromos");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Pais", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("WorldCupStickers.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioCromos");
                });
#pragma warning restore 612, 618
        }
    }
}
